all:
	javac -cp ../../../../../proj1/src usefoobar.java
run:
	java -cp ../../../../../proj1/src:../../../../../proj2/src use.foo.bar.usefoobar
clean:
	rm ../../../../../proj1/src/foo/bar/*.class ../../../../../proj2/src/use/foo/bar/*.class